# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.gpio:
        class: AppBundle\Service\GpioService
        arguments: []
    app.command.cooking:
        class: AppBundle\Command\AppCookingCommand
        tags:
            - { name: console.command }
