# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    adjust_temperature: 7.5
    thermometer_device_id: '28-0516a43dafff'
    relay_bcm_id: 7

services:
    gpio:
        class: PiPHP\GPIO\GPIO
        arguments: []

    app.gpio:
        class: AppBundle\Service\GpioService
        arguments:
            - '@gpio'
            - %adjust_temperature%
            - %thermometer_device_id%
            - %relay_bcm_id%
